const api=acquireVsCodeApi(),$=id=>document.getElementById(id);let state=null;
for(const id of ['create','package','refresh','open-vsx'])$(id).onclick=()=>api.postMessage({type:id});$('search').oninput=render;
function render(){if(!state)return;const query=$('search').value.trim().toLowerCase(),items=state.entries.filter(e=>(e.name+' '+e.description).toLowerCase().includes(query));const list=$('extensions');list.replaceChildren();$('empty').hidden=!!items.length;
 for(const entry of items){const row=document.createElement('article');row.className='extension';row.innerHTML='<svg viewBox="0 0 32 32" aria-hidden="true"><path d="M3 17h5l4-10 7 19 4-10h6"/></svg>';const info=document.createElement('div'),title=document.createElement('h3'),description=document.createElement('p'),meta=document.createElement('span');title.textContent=entry.name;description.textContent=entry.description;meta.className='meta';meta.textContent=`Paradise Code · ${entry.version} · ${entry.platforms.includes(state.platform)?'Available for this system':'macOS only'}`;info.append(title,description,meta);const actions=document.createElement('div');actions.className='row-actions';
  const button=(text,type,secondary=false)=>{const b=document.createElement('button');b.textContent=text;b.disabled=state.busy;if(secondary)b.className='secondary';b.onclick=()=>api.postMessage({type,id:entry.id});actions.append(b);return b};
  if(entry.installed){button('Open','open');if(entry.installed!==entry.version)button('Update','install');button('Remove','remove',true)}else{const b=button('Install','install');b.disabled=state.busy||!entry.platforms.includes(state.platform)}row.append(info,actions);list.append(row);
 }
}
window.addEventListener('message',({data:m})=>{if(m.type==='error'){$('error').textContent=m.message;$('error').hidden=false;return}if(m.type!=='state')return;state=m;$('error').hidden=true;$('connection').textContent=m.offline?'Offline · using the catalog bundled with this release.':'Connected to the Paradise catalog · packages verified before installation.';render()});api.postMessage({type:'ready'});
